--Check if FILES schema exists, if not create it
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'FILES')
	EXEC('CREATE SCHEMA FILES');
GO

IF OBJECT_ID('FILES.FilesDetails') IS NULL
	CREATE TABLE FILES.FilesDetails (
		FileId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		FileName NVARCHAR(255) NOT NULL,
		FileType NVARCHAR(50) NOT NULL,
		UploadedBy NVARCHAR(255) NOT NULL,
		UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		UserId UNIQUEIDENTIFIER NOT NULL,
		Content VARBINARY(MAX) NOT NULL,
		PRIMARY KEY (FileId)
	)
GO

